In [1]:
import pandas as pd

In [2]:

df = pd.read_csv("EWR_Enhanced1.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         493 non-null    float64
 1   Date             500 non-null    str
 2   Customer_Name    500 non-null    str
 3   Customer_Age     500 non-null    int64
 4   Product          500 non-null    str
 5   Category         500 non-null    str
 6   Price            500 non-null    float64
 7   Quantity         500 non-null    int64
 8   Total_Sales      500 non-null    float64
 9   Discount (%)     500 non-null    int64
 10  Final_Sales      500 non-null    float64
 11  Region           500 non-null    str
 12  Payment_Method   500 non-null    str
 13  Delivery_Status  500 non-null    str
 14  demo_col         500 non-null    int64
dtypes: float64(4), int64(4), str(7)
memory usage: 58.7 KB

In [4]:
df.head(10)

,Order_ID,Date,Customer_Name,Customer_Age,Product,Category,Price,Quantity,Total_Sales,Discount (%),Final_Sales,Region,Payment_Method,Delivery_Status,demo_col
0,NaN,14-09-2024,Abha Mandal,40,Fiction,Books,348.29,10,3482.90,16,2925.64,South,Cash,Pending,1
1,6285.0,20-03-2024,Saksham Dewan,22,Smartwatch,Electronics,330.21,10,3302.10,23,2542.62,East,Debit Card,Delivered,2
2,2931.0,16-03-2024,Gautam Samra,31,Moisturizer,Beauty,218.84,5,1094.20,47,579.93,South,Credit Card,Delivered,3
3,7980.0,19-12-2024,Rajata Goyal,24,Smartphone,Electronics,325.36,2,650.72,49,331.87,North,Credit Card,Delivered,4
4,2407.0,03-09-2024,Chaaya Swamy,40,Fiction,Books,419.22,8,3353.76,29,2381.17,South,UPI,Returned,5
5,9952.0,28-11-2024,Turvi Shetty,27,Perfume,Beauty,229.22,6,1375.32,8,1265.29,South,Debit Card,Delivered,6
6,3583.0,06-01-2024,Yasti Loke,19,Foundation,Beauty,250.76,1,250.76,48,130.40,North,UPI,Pending,7
7,3380.0,03-02-2024,Onkar Agarwal,26,Jacket,Clothing,318.05,4,1272.20,24,966.87,West,Cash,Delivered,8
8,4197.0,17-07-2024,Frado Virk,39,Smartphone,Electronics,312.29,5,1561.45,24,1186.70,East,UPI,Returned,9
9,1092.0,26-08-2024,Hitesh Raghavan,32,T-Shirt,Clothing,200.62,10,2006.20,5,1186.70,East,Cash,Returned,10

In [5]:
df.describe()

,Order_ID,Customer_Age,Price,Quantity,Total_Sales,Discount (%),Final_Sales,demo_col
count,493.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,5533.845842,41.304000,258.892860,5.522000,1433.097920,27.690000,1026.801600,250.500000
std,2563.689632,13.260137,138.398612,2.941227,1168.856345,13.415881,837.599783,144.481833
min,1042.000000,18.000000,10.050000,1.000000,12.390000,5.000000,6.200000,1.000000
25%,3341.000000,30.000000,144.085000,3.000000,447.210000,16.000000,308.777500,125.750000
50%,5501.000000,41.000000,254.480000,5.000000,1096.145000,27.000000,801.870000,250.500000
75%,7736.000000,52.000000,375.562500,8.000000,2164.505000,40.000000,1528.822500,375.250000
max,9982.000000,65.000000,499.490000,10.000000,4978.300000,50.000000,4348.430000,500.000000

In [ ]:
df.isnull().sum()

Order_ID           7
Date               0
Customer_Name      0
Customer_Age       0
Product            0
Category           0
Price              0
Quantity           0
Total_Sales        0
Discount (%)       0
Final_Sales        0
Region             0
Payment_Method     0
Delivery_Status    0
demo_col           0
dtype: int64