In [1]:
import pandas as pd
df = pd.read_csv('tumor_analysis.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [2]:
df.shape

(569, 33)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), str(1)
memory usage: 147.4 KB

In [4]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [5]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [6]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

In [7]:
df["Unnamed: 32"].unique()

array([nan])

In [8]:
df.drop('Unnamed: 32', axis =1, inplace = True)

In [10]:
df.dtypes

id                           int64
diagnosis                      str
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [11]:
df['id'].unique()

array([   842302,    842517,  84300903,  84348301,  84358402,    843786,
          844359,  84458202,    844981,  84501001,    845636,  84610002,
          846226,    846381,  84667401,  84799002,    848406,  84862001,
          849014,   8510426,   8510653,   8510824,   8511133,    851509,
          852552,    852631,    852763,    852781,    852973,    853201,
          853401,    853612,  85382601,    854002,    854039,    854253,
          854268,    854941,    855133,    855138,    855167,    855563,
          855625,    856106,  85638502,    857010,  85713702,     85715,
          857155,    857156,    857343,    857373,    857374,    857392,
          857438,  85759902,    857637,    857793,    857810,    858477,
          858970,    858981,    858986,    859196,  85922302,    859283,
          859464,    859465,    859471,    859487,    859575,    859711,
          859717,    859983,   8610175,   8610404,   8610629,   8610637,
         8610862,   8610908,    861103,   8611161,   8611555,   8611792,
         8612080,   8612399,  86135501,  86135502,    861597,    861598,
          861648,    861799,    861853,    862009,    862028,     86208,
           86211,    862261,    862485,    862548,    862717,    862722,
          862965,    862980,    862989,    863030,    863031,    863270,
           86355,    864018,    864033,     86408,     86409,    864292,
          864496,    864685,    864726,    864729,    864877,    865128,
          865137,     86517,    865423,    865432,    865468,     86561,
          866083,    866203,    866458,    866674,    866714,      8670,
        86730502,    867387,    867739,    868202,    868223,    868682,
          868826,    868871,    868999,    869104,    869218,    869224,
          869254,    869476,    869691,  86973701,  86973702,    869931,
       871001501, 871001502,   8710441,     87106,   8711002,   8711003,
         8711202,   8711216,    871122,    871149,   8711561,   8711803,
          871201,   8712064,   8712289,   8712291,     87127,   8712729,
         8712766,   8712853,  87139402,     87163,     87164,    871641,
          871642,    872113,    872608,  87281702,    873357,    873586,
          873592,    873593,    873701,    873843,    873885,    874158,
          874217,    874373,    874662,    874839,    874858,    875093,
          875099,    875263,  87556202,    875878,    875938,    877159,
          877486,    877500,    877501,    877989,    878796,     87880,
           87930,    879523,    879804,    879830,   8810158,   8810436,
       881046502,   8810528,   8810703, 881094802,   8810955,   8810987,
         8811523,   8811779,   8811842,  88119002,   8812816,   8812818,
         8812844,   8812877,   8813129,  88143502,  88147101,  88147102,
        88147202,    881861,    881972,  88199202,  88203002,  88206102,
          882488,  88249602,  88299702,    883263,    883270,  88330202,
        88350402,    883539,    883852,  88411702,    884180,    884437,
          884448,    884626,  88466802,    884689,    884948,  88518501,
          885429,   8860702,    886226,    886452,  88649001,    886776,
          887181,  88725602,    887549,    888264,    888570,    889403,
          889719,  88995002,   8910251,   8910499,   8910506,   8910720,
         8910721,   8910748,   8910988,   8910996,   8911163,   8911164,
         8911230,   8911670,   8911800,   8911834,   8912049,   8912055,
           89122,   8912280,   8912284,   8912521,   8912909,      8913,
         8913049,  89143601,  89143602,      8915,    891670,    891703,
          891716,    891923,    891936,    892189,    892214,    892399,
          892438,    892604,  89263202,    892657,     89296,    893061,
           89344,     89346,    893526,    893548,    893783,  89382601,
        89382602,    893988,    894047,    894089,    894090,    894326,
          894329,    894335,    894604,    894618,    894855,    895100,
        89511501,  89511502,     89524,    895299,   8953902,    895633,
          896839,    896864,    897132,    897137,    897374,  89742801,
          897604,    897630,    897880,     89812,     89813,    898143,
           89827,    898431,  89864002,    898677,    898678,     89869,
          898690,    899147,    899187,    899667,    899987,   9010018,
          901011,   9010258,   9010259,    901028,   9010333, 901034301,
       901034302,    901041,   9010598,   9010872,   9010877,    901088,
         9011494,   9011495,   9011971,   9012000,   9012315,   9012568,
         9012795,    901288,   9013005,    901303,    901315,   9013579,
         9013594,   9013838,    901549,    901836,     90250,     90251,
          902727,     90291,    902975,    902976,    903011,     90312,
        90317302,    903483,    903507,    903516,    903554,    903811,
        90401601,  90401602,    904302,    904357,  90439701,    904647,
          904689,      9047,    904969,    904971,    905189,    905190,
        90524101,    905501,    905502,    905520,    905539,    905557,
          905680,    905686,    905978,  90602302,    906024,    906290,
          906539,    906564,    906616,    906878,    907145,    907367,
          907409,     90745,  90769601,  90769602,    907914,    907915,
          908194,    908445,    908469,    908489,    908916,    909220,
          909231,    909410,    909411,    909445,  90944601,    909777,
         9110127,   9110720,   9110732,   9110944,    911150, 911157302,
         9111596,   9111805,   9111843,    911201,    911202,   9112085,
         9112366,   9112367,   9112594,   9112712, 911296201, 911296202,
         9113156, 911320501, 911320502,   9113239,   9113455,   9113514,
         9113538,    911366,   9113778,   9113816,    911384,   9113846,
          911391,    911408,    911654,    911673,    911685,    911916,
          912193,     91227,    912519,    912558,    912600,    913063,
          913102,    913505,    913512,    913535,  91376701,  91376702,
          914062,    914101,    914102,    914333,    914366,    914580,
          914769,     91485,    914862,     91504,     91505,    915143,
          915186,    915276,  91544001,  91544002,    915452,    915460,
           91550,    915664,    915691,    915940,  91594602,    916221,
          916799,    916838,    917062,    917080,    917092,  91762702,
           91789,    917896,    917897,     91805,  91813701,  91813702,
          918192,    918465,     91858,  91903901,  91903902,  91930402,
          919537,    919555,  91979701,    919812,    921092,    921362,
          921385,    921386,    921644,    922296,    922297,    922576,
          922577,    922840,    923169,    923465,    923748,    923780,
          924084,    924342,    924632,    924934,    924964,    925236,
          925277,    925291,    925292,    925311,    925622,    926125,
          926424,    926682,    926954,    927241,     92751])

In [12]:
df.drop("id",axis = 1,inplace = True)

In [13]:
df['diagnosis'].unique()

<ArrowStringArray>
['M', 'B']
Length: 2, dtype: str

In [ ]:
df["diagnosis"] = df["diagnosis"].get