In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("SMSSpamCollection.csv",sep="\t",names=["Label","Messege"])

In [37]:
df.head(1)

  Label                                            Messege
0   ham  Go until jurong point, crazy.. Available only ...

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Label    5572 non-null   str
 1   Messege  5572 non-null   str
dtypes: str(2)
memory usage: 542.9 KB

In [39]:
df.describe()

       Label                 Messege
count   5572                    5572
unique     2                    5169
top      ham  Sorry, I'll call later
freq    4825                      30

In [40]:
df.shape

(5572, 2)

In [41]:
df.isnull().sum()

Label      0
Messege    0
dtype: int64

In [42]:
df[df.duplicated]

     Label                                            Messege
103    ham  As per your request 'Melle Melle (Oru Minnamin...
154    ham  As per your request 'Melle Melle (Oru Minnamin...
207    ham  As I entered my cabin my PA said, '' Happy B'd...
223    ham                             Sorry, I'll call later
326    ham                   No calls..messages..missed calls
...    ...                                                ...
5524  spam  You are awarded a SiPix Digital Camera! call 0...
5535   ham  I know you are thinkin malaria. But relax, chi...
5539   ham                         Just sleeping..and surfing
5553   ham                        Hahaha..use your brain dear
5558   ham                             Sorry, I'll call later

[403 rows x 2 columns]

In [43]:
df.drop_duplicates(inplace=True)

In [44]:
df

     Label                                            Messege
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [45]:
df.shape

(5169, 2)

In [46]:
df.head()

  Label                                            Messege
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [47]:
df["Label"].unique()

<ArrowStringArray>
['ham', 'spam']
Length: 2, dtype: str